//
//  ViewController.swift
//  SquallTest
//
//  Created by Dmitry Zhukov on 08.11.16.
//  Copyright © 2016 Dmitry Zhukov. All rights reserved.
//

import UIKit
import Squall

class ViewController: UIViewController {
    
    private var animationHipster: SLSquallAnimation!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        // old one is a base64 string (generated by Squall 1.006 extension)
        // new one is a JSON (generated by Squall 2.0 extension)
        // we initialize animation that way (from Bundle), cause in our app
        // sqa animation files are stored not in the main bundle
        
//        let animationPath = NSBundle.mainBundle().pathForResource("HipsterMoonwalkOld", ofType: "sqa")!
        let animationPath = NSBundle.mainBundle().pathForResource("HipsterMoonwalkNew", ofType: "sqa")!
        animationHipster = SLSquallAnimation.init(fromPath: animationPath, error: nil)
        
        view.layoutIfNeeded()
        animationHipster.frame = view.layer.frame
        view.layer.addSublayer(animationHipster)
    }
    
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        animationHipster.play()
    }

}

